apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE_NAME}-preview
  labels:
    app: ${APP_NAME}
    role: preview
    version: ${SLOT}
spec:
  type: NodePort
  selector:
    app: ${APP_NAME}
    version: ${SLOT}
  ports:
    - name: http
      port: 3000
      targetPort: http
      nodePort: 30091
