name: Release API Blue-Green

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      image_tag:
        description: Docker image tag to deploy from manual dispatch.
        required: true
        default: v1.0.0
        type: string

permissions:
  contents: read

jobs:
  usar-receta-compartida:
    name: Build, publish and deploy
    uses: OscarNeira/AAU1104-OscarNeira-Primary/.github/workflows/deploy-api.yaml@main
    with:
      image-name: demo-api
      image-tag: ${{ github.event_name == 'workflow_dispatch' && inputs.image_tag || github.ref_name }}
      k3s-server-public-ip: ${{ vars.K3S_SERVER_PUBLIC_IP }}
      k8s-namespace: ${{ vars.K8S_NAMESPACE || 'orders' }}
      app-name: orders
      service-name: orders-svc
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      EA2_SSH_PRIVATE_KEY: ${{ secrets.EA2_SSH_PRIVATE_KEY }}
